-- MySQL Script generated by MySQL Workbench
-- Fri Jan 19 12:28:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jrj
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jrj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jrj` DEFAULT CHARACTER SET utf8 ;
USE `jrj` ;

-- -----------------------------------------------------
-- Table `jrj`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jrj`.`customer` (
  `CustomerID` INT(11) NOT NULL AUTO_INCREMENT,
  `LastName` CHAR(35) NOT NULL,
  `FirstName` CHAR(25) NOT NULL,
  `Phone` CHAR(12) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `num_of_purchases` INT(2) NULL COMMENT 'When the number of purchases reaches 10, the next purchase will receive a discount equal to 50% of the average purchase with is 0.50*(total/10). And the number of purchases and total will be reset to 0. \n',
  `puchase_totals` INT(11) NULL COMMENT 'When the number of purchases reaches 10, the next purchase will receive a discount equal to 50% of the average purchase with is 0.50*(total/10). And the number of purchases and total will be reset to 0. \n',
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jrj`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jrj`.`item` (
  `ItemNumber` INT(11) NOT NULL AUTO_INCREMENT,
  `ItemDescription` VARCHAR(255) NOT NULL,
  `Cost` DECIMAL(9,2) NOT NULL,
  `ArtistLastName` CHAR(35) NULL DEFAULT NULL,
  `ArtistFirstName` CHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`ItemNumber`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jrj`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jrj`.`purchase` (
  `InvoiceNumber` INT(11) NOT NULL AUTO_INCREMENT,
  `InvoiceDate` DATE NOT NULL,
  `PreTaxAmount` DECIMAL(9,2) NOT NULL,
  `CustomerID` INT(11) NOT NULL,
  PRIMARY KEY (`InvoiceNumber`),
  INDEX `PURCHASE_CUSTOMER_FK` (`CustomerID` ASC),
  CONSTRAINT `PURCHASE_CUSTOMER_FK`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `jrj`.`customer` (`CustomerID`)
    ON DELETE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jrj`.`purchase_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jrj`.`purchase_item` (
  `InvoiceNumber` INT(11) NOT NULL,
  `InvoiceLineNumber` INT(11) NOT NULL,
  `ItemNumber` INT(11) NOT NULL,
  `RetailPrice` DECIMAL(9,2) NOT NULL,
  `AwardDiscount` FLOAT NULL COMMENT 'the discount (if any) given for this purchase.\n',
  PRIMARY KEY (`InvoiceNumber`, `InvoiceLineNumber`),
  INDEX `PURCHASE_ITEM_ITEM_FK` (`ItemNumber` ASC),
  CONSTRAINT `PURCHASE_ITEM_ITEM_FK`
    FOREIGN KEY (`ItemNumber`)
    REFERENCES `jrj`.`item` (`ItemNumber`)
    ON DELETE NO ACTION,
  CONSTRAINT `PURCHASE_ITEM_PURCHASE_FK`
    FOREIGN KEY (`InvoiceNumber`)
    REFERENCES `jrj`.`purchase` (`InvoiceNumber`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jrj`.`Artisits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jrj`.`Artisits` (
  `idArtisits` INT NOT NULL AUTO_INCREMENT,
  `ArtistLastName` CHAR(35) NULL DEFAULT NULL,
  `ArtistFirstName` CHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`idArtisits`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jrj`.`Styles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jrj`.`Styles` (
  `idStyles` INT NOT NULL,
  `Engagement Ring` TINYINT NULL,
  `Diamond Ring` TINYINT NULL,
  `Earring` TINYINT NULL,
  `Bracelet` TINYINT NULL,
  `Necklace` TINYINT NULL,
  PRIMARY KEY (`idStyles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jrj`.`Artisits_has_Styles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jrj`.`Artisits_has_Styles` (
  `Artisits_idArtisits` INT NOT NULL,
  `Styles_idStyles` INT NOT NULL,
  PRIMARY KEY (`Artisits_idArtisits`, `Styles_idStyles`),
  INDEX `fk_Artisits_has_Styles_Styles1_idx` (`Styles_idStyles` ASC),
  INDEX `fk_Artisits_has_Styles_Artisits1_idx` (`Artisits_idArtisits` ASC),
  CONSTRAINT `fk_Artisits_has_Styles_Artisits1`
    FOREIGN KEY (`Artisits_idArtisits`)
    REFERENCES `jrj`.`Artisits` (`idArtisits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artisits_has_Styles_Styles1`
    FOREIGN KEY (`Styles_idStyles`)
    REFERENCES `jrj`.`Styles` (`idStyles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jrj`.`customer_likes_Artisits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jrj`.`customer_likes_Artisits` (
  `customer_CustomerID` INT(11) NOT NULL,
  `Artisits_idArtisits` INT NOT NULL,
  PRIMARY KEY (`customer_CustomerID`, `Artisits_idArtisits`),
  INDEX `fk_customer_has_Artisits_Artisits1_idx` (`Artisits_idArtisits` ASC),
  INDEX `fk_customer_has_Artisits_customer1_idx` (`customer_CustomerID` ASC),
  CONSTRAINT `fk_customer_has_Artisits_customer1`
    FOREIGN KEY (`customer_CustomerID`)
    REFERENCES `jrj`.`customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_Artisits_Artisits1`
    FOREIGN KEY (`Artisits_idArtisits`)
    REFERENCES `jrj`.`Artisits` (`idArtisits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jrj`.`customer_likes_Styles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jrj`.`customer_likes_Styles` (
  `customer_CustomerID` INT(11) NOT NULL,
  `Styles_idStyles` INT NOT NULL,
  PRIMARY KEY (`customer_CustomerID`, `Styles_idStyles`),
  INDEX `fk_customer_has_Styles_Styles1_idx` (`Styles_idStyles` ASC),
  INDEX `fk_customer_has_Styles_customer1_idx` (`customer_CustomerID` ASC),
  CONSTRAINT `fk_customer_has_Styles_customer1`
    FOREIGN KEY (`customer_CustomerID`)
    REFERENCES `jrj`.`customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_Styles_Styles1`
    FOREIGN KEY (`Styles_idStyles`)
    REFERENCES `jrj`.`Styles` (`idStyles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
